### ISSUE TITLE
`AutoCompleteList` doesn't work properly when combining mapped items from an array with static children

### ISSUE THREAD

**Issue by flayner2** [anubra266/choc-autocomplete#146] opened 2022-05-19 18:01 UTC
The `AutoCompleteList` component doesn't behave as expected when its children are a combination of both mapped items from an array and static components. In my app, I update an array of `paper` objects with the `useState` hook with api calls that listen to `onChange` events on the `AutoCompleteInput`. The array starts empty, and is then populated as the user types. As of now, this works. But, if I add other components inside the `AutoCompleteList` after the array is mapped, the suggestions stop working for the papers array (although they work for the values of the static components). This bug happens even if I map through an array that starts populated, such as the countries array from the examples. For example (I omitted the `AutoComplete` wrapper component for clarity):

```javascript
<AutoCompleteList>
    {/* These items will not appear in the suggestions... */}
    {papers.map((paper) => (
       <AutoCompleteItem
            key={paper.pmid}
            value={paper.title}
      >
      </AutoCompleteItem>
    ))}
    {/* ...but these will: */}
    <AutoCompleteItem key={1} value="123"></AutoCompleteItem>
    <AutoCompleteItem key={2} value="1234"></AutoCompleteItem>
</AutoCompleteList>
```

This is relevant, for example, when using a component as an observable for on-scroll api pagination, like in the following:

```javascript
<AutoCompleteList>
    {papers.map((paper) => (
       <AutoCompleteItem
            key={paper.pmid}
            value={paper.title}
      >
      </AutoCompleteItem>
    ))}
    {/* The `Box` below renders, but the suggestions list doesn't */}
    <Box id="watcher" />{/* This component would be used for the Intersection Observer API */}
    {/* This could optionally be an empty `AutoCompleteItem` so it works with the `emptyState` prop from `AutoComplete */}
    {/* since `emptyState` only cares about `AutoCompleteItem`s */}
    <AutoCompleteItem value="" id="watcher" />
</AutoCompleteList>
```

The box is rendered, which would allow me to use it as an observable, but the suggestion list isn't, so it basically breaks the component's functionality. Also, in addition to that, I found another bug: whenever i use either a static string or a number converted to a string as the `AutoCompleteItem`'s value inside the map, the suggestions list also breaks *but only while typing* because, as soon as I unfocus the component, the suggestions list is rendered correctly. For example:

```javascript
<AutoCompleteList>
    {papers.map((paper) => (
       <AutoCompleteItem
            key={paper.pmid}
            value={paper.pmid.toString()} {/* Suggestion list doesn't update while typing */ }
      >
      </AutoCompleteItem>
    ))}
</AutoCompleteList>
```

Or:

```javascript
<AutoCompleteList>
    {papers.map((paper) => (
       <AutoCompleteItem
            key={paper.pmid}
            value="test" {/* Also doesn't show while typing */}
      >
      </AutoCompleteItem>
    ))}
</AutoCompleteList>
```

Tell me if you require any additional information.

**Comment by chrismorison-wt** [comment] 2022-06-02 02:56
Did you get anywhere with this?

I'm having a similar issue, but mine is related to having an `<AutoCompleteGroupTitle>`.

Using the exact same Groups demo code from the readme, this grouped list has the same problem you're having:

```jsx
          <AutoCompleteList>
            {Object.entries(continents).map(([continent, countries], co_id) => (
              <AutoCompleteGroup key={co_id} showDivider>
                <AutoCompleteGroupTitle textTransform="capitalize">
                  {continent}
                </AutoCompleteGroupTitle>
                {/* These items will not appear in the suggestions... */}
                {countries.map((country, c_id) => (
                  <AutoCompleteItem
                    key={c_id}
                    value={country}
                    textTransform="capitalize"
                  >
                    {country}
                  </AutoCompleteItem>
                ))}
                {/* ...but these will: */}
                <AutoCompleteItem key={2} value="1234"></AutoCompleteItem>
              </AutoCompleteGroup>
            ))}
          </AutoCompleteList>
```
<img width="238" alt="image" src="https://user-images.githubusercontent.com/104949709/171542583-d29681b1-3b49-4945-af28-dcd64d099b9f.png">

But remove the group titles and it renders all items:

```jsx
          <AutoCompleteList>
            {Object.entries(continents).map(([continent, countries], co_id) => (
              <AutoCompleteGroup key={co_id} showDivider>
                {/* These items will appear in the suggestions... */}
                {countries.map((country, c_id) => (
                  <AutoCompleteItem
                    key={c_id}
                    value={country}
                    textTransform="capitalize"
                  >
                    {country}
                  </AutoCompleteItem>
                ))}
              </AutoCompleteGroup>
            ))}
          </AutoCompleteList>
```
<img width="233" alt="image" src="https://user-images.githubusercontent.com/104949709/171542893-cc03354e-e8ea-4310-9db8-449f6729f350.png">

I've updated to latest version `4.22`

**Comment by flayner2** [comment] 2022-06-02 03:04
> Did you get anywhere with this?
> 
> I'm having a similar issue, but mine is related to having an `<AutoCompleteGroupTitle>`.
> 
> Using the exact same Groups demo code from the readme, this grouped list has the same problem you're having:
> 
> ```js
>           <AutoCompleteList>
>             {Object.entries(continents).map(([continent, countries], co_id) => (
>               <AutoCompleteGroup key={co_id} showDivider>
>                 <AutoCompleteGroupTitle textTransform="capitalize">
>                   {continent}
>                 </AutoCompleteGroupTitle>
>                 {/* These items will not appear in the suggestions... */}
>                 {countries.map((country, c_id) => (
>                   <AutoCompleteItem
>                     key={c_id}
>                     value={country}
>                     textTransform="capitalize"
>                   >
>                     {country}
>                   </AutoCompleteItem>
>                 ))}
>                 {/* ...but these will: */}
>                 <AutoCompleteItem key={2} value="1234"></AutoCompleteItem>
>               </AutoCompleteGroup>
>             ))}
>           </AutoCompleteList>
> ```
> 
> <img alt="image" width="238" src="https://user-images.githubusercontent.com/104949709/171542583-d29681b1-3b49-4945-af28-dcd64d099b9f.png">
> 
> But remove the group titles and it renders all items:
> 
> ```js
>           <AutoCompleteList>
>             {Object.entries(continents).map(([continent, countries], co_id) => (
>               <AutoCompleteGroup key={co_id} showDivider>
>                 {/* These items will appear in the suggestions... */}
>                 {countries.map((country, c_id) => (
>                   <AutoCompleteItem
>                     key={c_id}
>                     value={country}
>                     textTransform="capitalize"
>                   >
>                     {country}
>                   </AutoCompleteItem>
>                 ))}
>               </AutoCompleteGroup>
>             ))}
>           </AutoCompleteList>
> ```
> 
> <img alt="image" width="233" src="https://user-images.githubusercontent.com/104949709/171542893-cc03354e-e8ea-4310-9db8-449f6729f350.png">
> 
> I've updated to latest version `4.22`

Nope, had no luck at all with it, I decided to migrate to [react-aria's useComboBox](https://react-spectrum.adobe.com/react-aria/useComboBox.html) instead as anubra himself suggested [here](https://github.com/anubra266/choc-autocomplete/issues/147#issue-1243248868).

**Comment by chrismorison-wt** [comment] 2022-06-02 16:38
I managed to get my example working.  I figured that the `AutoCompleteGroup` didn't like a mixture of static elements and arrays of elements, so I combined the static element (in my case the group title) into the array:

```jsx
          <AutoCompleteList>
            {groups.map((group) => (
              <AutoCompleteGroup key={group.label || '_default'}>
                {[group.label, ...group.options].filter(a => a).map((option) =>
                  typeof option === 'string'
                  ? <AutoCompleteGroupTitle key="_title">
                      {group.label}
                    </AutoCompleteGroupTitle>
                  : <AutoCompleteItem key={option.value} value={option.value} label={option.label}>
                      {option.label}
                    </AutoCompleteItem>
                )}
              </AutoCompleteGroup>
            ))}
          </AutoCompleteList>
```
(I include the `.filter(a => a)` bit only because I have some items which are ungrouped and therefore in a group with a blank label)

**Comment by flayner2** [comment] 2022-06-02 19:26
> I managed to get my example working. I figured that the `AutoCompleteGroup` didn't like a mixture of static elements and arrays of elements, so I combined the static element (in my case the group title) into the array:

I thought about doing that as well, but turns out react-aria's `useCombobox` fits my necessities much better, since it is really good at dealing with async data (with the help of react-stately's `useAsyncList`), it is much more customizable and has inbuilt support for API pagination.

**Comment by jamesopti** [comment] 2022-08-21 15:33
I can confirm this behavior worked in `v4.22.0` and has regressed in `v5.1.1` as I work on our React 18 upgrade.

I suspect theres a bug in the upgraded version of react-nanny where the children are found: https://github.com/anubra266/choc-autocomplete/blob/v5.1.1/src/helpers/items.ts#L26-L29


I was able to work around it by just concatenating all my `<AutoCompleteItem>` instances together.


```ts
users
  .map(({ id, email }) => {
    return <AutoCompleteItem ... />
  })
  .concat(
    users2
      .map(({ id, email }) => {
        return <AutoCompleteItem ... />
      })
  )
```

**Comment by jamesopti** [comment] 2022-08-23 19:39
@anubra266 Any thoughts on this one? Is this perhaps a bug in react-nanny?

**Comment by abrgr** [comment] 2022-11-01 22:42
Definitely a react-nanny bug.

In https://github.com/TheSpicyMeatball/react-nanny/blob/fc64a4513397e6600ecdc7c0362587fb473781e4/src/getChildren/index.ts#L43

should be:

```
    if (Array.isArray(child)) { // this is the new case to handle
      output = [...output, ...getChildrenDeep<T, TC>(child, predicate)];
    }

    if ((child as NannyNode).props?.children) {
      output = [...output, ...getChildrenDeep<T, TC>((child as NannyNode).props.children, predicate)];
    }
```

Right now, react-nanny doesn't handle arrays as children.

**Comment by Daidalos117** [comment] 2022-11-10 08:23
should be fixed in the newest release, check it out guys

**Closed** 2022-11-10 10:22 UTC
