### ISSUE TITLE
Is there a way to list all when calling `onOpen`?

### ISSUE THREAD

**Issue by meta-meta** [anubra266/choc-autocomplete#258] opened 2024-07-26 20:52 UTC
I'm using `AutoComplete` as a controlled component with a button in `<InputRightElement>` which calls `isOpen` on click. The issue I'm having is that if there is already a value selected, the list is filtered when I click the button.

My current workaround looks like this:
```
  const [disableFilter, setDisableFilter] = useState(false);
  
(...)

  <AutoComplete
    disableFilter={disableFilter}
    listAllValuesOnFocus={true}
    openOnFocus
    value={selectedValue}          
  >

(...)

<AutoCompleteInput onFocus={() => setDisableFilter(false)}>

(...)

 <InputRightElement>
    <Button onClick={() => {
      if (isOpen) onClose();
      else {
        setDisableFilter(true);
        onOpen();
      }
    }}>
      {isOpen
        ? <ChevronUpIcon/>
        : <ChevronDownIcon/>}
    </Button>
  </InputRightElement>
```

I think a simple solution would be to implement a `listAllValuesOnOpen`, either in addition to `listAllValuesOnFocus` or replacing `listAllValuesOnFocus`. I'm new to the component though so not aware of all the combinations of how folks are using it.

**Comment by Kysluss** [comment] 2024-07-28 20:12
Hi @meta-meta ,

I'm not able to reproduce the issue you're seeing.  Below is a quickly modified version of the `WithIcon` example out on the code sandbox.  If you select something and then click on the input again, all of the items are shown.  Let me know if I've missed something.

```js

export default function MyExample() {
  const options = ["apple", "appoint", "zap", "cap", "japan"];
  const [disableFilter, setDisableFilter] = useState(false);
  const { isOpen, onOpen, onClose } = useDisclosure();
  const [selectedValue, setSelectedValue] = useState("apple");
  return (
    <Stack direction="column">
      <AutoComplete
        disableFilter={disableFilter}
        listAllValuesOnFocus={true}
        openOnFocus
        value={selectedValue}
        onChange={setSelectedValue}
      >
        <InputGroup>
          <InputLeftElement
            pointerEvents="none"
            color="inherit"
            fontSize="1.2em"
          >
            <Icon boxSize="16px" viewBox="0 0 24 24" focusable="false">
              <path
                fill="currentColor"
                d="M23.384,21.619,16.855,15.09a9.284,9.284,0,1,0-1.768,1.768l6.529,6.529a1.266,1.266,0,0,0,1.768,0A1.251,1.251,0,0,0,23.384,21.619ZM2.75,9.5a6.75,6.75,0,1,1,6.75,6.75A6.758,6.758,0,0,1,2.75,9.5Z"
              ></path>
            </Icon>
          </InputLeftElement>
          <AutoCompleteInput
            variant="filled"
            placeholder="Search..."
            onFocus={() => setDisableFilter(false)}
          />
          <InputRightElement>
            <Button
              onClick={() => {
                if (isOpen) onClose();
                else {
                  setDisableFilter(true);
                  onOpen();
                }
              }}
            >
              {isOpen ? "^" : "V"}
            </Button>
          </InputRightElement>
        </InputGroup>
        <AutoCompleteList>
          {options.map((option, oid) => (
            <AutoCompleteItem
              key={`option-${oid}`}
              value={option}
              textTransform="capitalize"
            >
              {option}
            </AutoCompleteItem>
          ))}
        </AutoCompleteList>
      </AutoComplete>
    </Stack>
  );
}
```

**Comment by meta-meta** [comment] 2024-07-29 15:50
Hi @Kysluss, here's a sandbox with the issue and the workaround side by side. Clicking the input on either works just fine. You'll see the issue when clicking on the button. 
![image](https://github.com/user-attachments/assets/61334c27-d439-4b11-b867-b19b3fe47cf2)

**Comment by Kysluss** [comment] 2024-08-01 00:19
Okay, so the issue that is when you trigger `onOpen` from the render function, it doesn't focus the `input` element.  I think I can fix this pretty quick.

**Comment by Kysluss** [comment] 2024-08-01 00:24
@meta-meta Do you want the user to be able to type once the items are displayed?  I have this specific issue resolved, but you can't type to filter the items after you click the button.  Maybe this could be controlled by a separate prop `focusInputOnOpen` to allow you to control your specific use case.

**Comment by Kysluss** [comment] 2024-08-01 00:51
The issue you were seeing should be fixed in [v5.5.2](https://github.com/anubra266/choc-autocomplete/releases/tag/v5.5.2), but I have also opened #259 for a potential enhancement allowing you to also focus/blur the input if desired.  Any input you have would be appreciated.

I am going to try and close the other open issues this week with a plan to release those at the weekend.

**Closed by Kysluss** 2024-08-01 00:51 UTC

**Comment by meta-meta** [comment] 2024-08-01 01:39
That's great! Thanks @Kysluss . I think it's totally fine if the input is not focused, in fact this may be preferable in my case, which is a web app inside a VR app where focusing the input would cause a soft keyboard to pop up. This can be quite cumbersome so I predict some users will find a point-and-click interaction easier to deal with. Power users can click the input to type. In other words, a prop sounds like the way to go!

**Comment by Kysluss** [comment] 2024-08-01 01:41
Perfect.  Thank you for that input.  I plan on making that the default behavior, but I can see where it might be nice to have the input focusable.
