### ISSUE TITLE
Setting value to undefined or null does not clear input

### ISSUE THREAD

**Issue by chrisgco** [anubra266/choc-autocomplete#133] opened 2022-03-03 14:41 UTC
The autocomplete component seems to be semi controlled. If I set `value` and `onChange`, and set value to null or undefined, I expected the AutocompleteInput.

**Comment by aysegulkavakli** [comment] 2022-03-09 14:54
Same issue here +

**Comment by alvinoalvin** [comment] 2022-03-11 20:02
Same issue, tried setting the `restoreOnBlur` property to false as well, but am not getting any results in doing so.

**Comment by cruzlutor** [comment] 2022-03-30 02:34
I'm not sure if you guys are having the same issue I faced, but in my case, I fixed it in this way

```
...
const [value, setValue] = useState<string>('');
...
<AutoComplete
  openOnFocus
  multiple
  onChange={(vals) => console.log(vals)}
  onSelectOption={() => {
    setValue('');
  }}
  >
  <AutoCompleteInput
    value={value}
    onChange={(a) => {
      setValue(a.target.value);
    }}
  >
    {({ tags }) =>
      tags.map((tag, tid) => (
        <AutoCompleteTag
          key={tid}
          label={tag.label}
          onRemove={tag.onRemove}
        />
      ))
    }
  </AutoCompleteInput>
  <AutoCompleteList>
    {countries.map((country, cid) => (
      <AutoCompleteItem
        key={`option-${cid}`}
        value={country}
        textTransform="capitalize"
        _selected={{ bg: 'whiteAlpha.50' }}
        _focus={{ bg: 'whiteAlpha.100' }}
      >
        {country}
      </AutoCompleteItem>
    ))}
  </AutoCompleteList>
</AutoComplete>
```

**Comment by simecek-m** [comment] 2022-05-10 09:30
I think you need to use `restoreOnBlurIfEmpty` prop instead of `restoreOnBlur`.

**Comment by Kysluss** [comment] 2023-08-25 01:18
It seems like this issue was fixed by using `restoreOnBlurIfEmpty` and potentially also by some other changes that have happened since the initial post was made.  Doing some testing of my own, it seems the input is controllable in the manner you mention.  If there's still an issue, would you be able to supply a codesandbox reproducing the issue?

**Closed** 2023-09-13 00:26 UTC
Labels: bug
